#Make a file of subjects to keep for QC and strand alignment
#V1 - May 5, 2016 - Initial release

#Get command list
args <- commandArgs(trailingOnly = TRUE)

family_file <- args[1]
ancestry_file <- args[2]
ancestry_use <- args[3]
ibd_file <- args[4]
output_file <- paste(ancestry_file,"_",ancestry_use,".subjects",sep="")


 unlist_split <- function(x, ...)
  {
	toret <- unlist(strsplit(x, ...) )
	return(t(toret))
  }
 #Load in the first fam file generated by the qc script
  options(stringsAsFactors=F)
  dat <- read.table(family_file,header=F)
  names(dat) <- c("FIDL","IID","M","F","G","P")
  dat[,c("FID")] <- t(sapply(dat$FIDL,unlist_split,split="[/*]"))[,2]
	 
  ancestries <- read.table(ancestry_file,header=T)
  ibd <- read.table(ibd_file,header=T)
  
 #Take the majority homogenous population, we'll use that for HWE

  table(ancestries$bestpop_oneweek)
  anc_use <- subset(ancestries,bestpop_oneweek==ancestry_use & !(FID %in% ibd$FID & IID %in% ibd$IID))
  #Join on FID/IID with the * designations removed because that links the files
  dat_use <- merge(dat, anc_use,by=c("FID","IID"),suffixes=c("","_dontuse"))
  #dim(dat_use)[1] #Should equal to N of homogenous population in bestpop table
  print(paste("Using a sample of N =",dim(dat_use)[1], "for HWE, strand alignment check, QC related QQ/Manhattan plots association analysis"))

  write.table(subset(dat_use,select=c(FIDL,IID)),output_file,quote=F,row.names=F)
